name = "Herglotz_Lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ComplexAnalysis"]


[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
experimental.module = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0-rc2"

[[lean_lib]]
name = "ComplexAnalysis"

